site_name: 考研数学文档 Kmath
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      accent: pink
      primary: black
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      accent: pink
      primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - toc:
      permalink: true

repo_url: https://github.com/RadleyJiao/Kaoyan-Math-Doc
repo_name: RadleyJiao/Kaoyan-Math-Doc
plugins:
  - search:
      lang:
        - en
        - ja
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
  - stylesheets/extra.css
nav:
  - 高等数学:
    - 函数极限: 高等数学/函数极限.md
    - 数列极限: 高等数学/数列极限.md
    - 连续、间断与导数: 高等数学/连续、间断与导数.md
    - 中值定理: 高等数学/中值定理.md
    - 积分: 高等数学/积分.md
    - 微分方程: 高等数学/微分方程.md
    - 级数判敛: 高等数学/级数判敛.md
  - 线性代数:
    - 行列式与矩阵: 线性代数/行列式与矩阵.md
    - 秩与向量: 线性代数/秩与向量.md
    - 线性方程组: 线性代数/线性方程组.md
    - 特征值与特征向量: 线性代数/特征值与特征向量.md
  - 概率论:
    - chap1: chap1.md
  - 其他相关概念: 其他相关概念.md